### ISSUE TITLE
remove the option to have strict = FALSE for matching variable names

### ISSUE THREAD

**Issue by joethorley** [bcgov/shinyrems#113]
This is because the option is soft-deprecated in wqbc and is not very reliable.

**Comment by joethorley** [comment]
I also believe this is something we discussed in our group meetings

**Comment by sebdalgarno** [comment]
yes I've already removed it. strict = TRUE now happens behind the scenes with no option to user to change

**Comment by sebdalgarno** [comment]
sorry should have mentioned that you should install the package from phase_2 branch - that has latest changes
