### ISSUE TITLE
generate historic lookup

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/shinyrems#118]
currently historic lookup sits as data in the package. Since historic data now regenerated daily, should move to approach in 2yr data (caching lookup) to keep up to date

**Comment by HeatherGranger** [comment]
@joethorley @aylapear is this idea still relevant given how historic data is now downloaded with duckdb?

**Comment by joethorley** [comment]
@HeatherGranger - I think it is still relevant to keep the package up to date on a daily basis

**Comment by aylapear** [comment]
tied to issue #126

**Comment by aylapear** [comment]
if this pull request is accepted it will deal with this issue 
https://github.com/bcgov/rems/pull/69

**Comment by aylapear** [comment]
@HeatherGranger this could be closed as the pull request in rems was accepted. Try the app with historic data set (after updating rems) and if it suits what you expected this can be closed.
