### ISSUE TITLE
wqbc::tidy_ems_data no longer working

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/shinyrems#119]
Error in C_force_tz(time, tz = tzone, roll) : \n  CCTZ: Unrecognized timezone of the input vector: "Etc/GMT+8"\n

**Comment by ateucher** [comment]
That looks like there might be something wrong with your timezone database... `"Etc/GMT+8"` is a valid timezone.

```r
> lubridate::force_tz(Sys.time(), tzone = "Etc/GMT+8")
[1] "2021-01-18 14:29:42 -08"
```

**Comment by sebdalgarno** [comment]
yes I'm not exactly sure what is causing the issue. This is unrelated to the duckdb changes BTW...it occurred before I updated.

**Comment by joethorley** [comment]
This is an issue with lubridate 

https://github.com/tidyverse/lubridate/issues/928

not shinyrems and so we can close this issue @JessicaPenno .
