### ISSUE TITLE
'use_butler' issue for 4yr data

### ISSUE THREAD

**Issue by KeithTStory** [bcgov/shinyrems#121]
Error after storing 4yr data lookup table and initiating shiny app:

Listening on http://127.0.0.1:3205
Warning: Error in : 'use_butler' is not an exported object from 'namespace:waiter'
  77: stop
  76: getExportedValue
  75: ::
  72: shinyrems:::app_ui

**Comment by JessicaPenno** [comment]
@KeithTStory there has been an update to bcgov/rems, check it out and I will also send you some information.

**Comment by joethorley** [comment]
@KeithTStory - this should have been fixed with pull request https://github.com/bcgov/shinyrems/pull/120

Can you confirm (after installing the development version of shinyrems using `devtools::install_github("bcgov/shinyrems")`?

**Comment by KeithTStory** [comment]
@joethorley @JessicaPenno  

Thank you for looking into this. 

After trying your suggestions, I ran into:
      Error: Failed to install 'shinyrems' from GitHub:
        ERROR: failed to lock directory ‘C:\Users\kstory\R\win-library\3.6’ for modifying
      Try removing ‘C:\Users\kstory\R\win-library\3.6/00LOCK’

Removing 00LOCK did not work, nor did burn_it_down(), although I don't know whether the latter addresses this. 

Resolved by specifying installation options:
      devtools::install_github("bcgov/shinyrems", dependencies = TRUE, INSTALL_opts = "--no-lock")

**Comment by joethorley** [comment]
@KeithTStory - thanks for reporting that - I've not seen that before.

Did shinyrems then work for you?

**Comment by KeithTStory** [comment]
@joethorley 
Sorry for not specifying. It works and looks incredible. Thank you and the team for all the hard work.

**Comment by joethorley** [comment]
Thanks!

@JessicaPenno - you can close this issue.

**Comment by JessicaPenno** [comment]
closed
