### ISSUE TITLE
Downloading 2yr data issue

### ISSUE THREAD

**Issue by KeithTStory** [bcgov/shinyrems#122]
Downloading latest '2yr' EMS data from BC Data Catalogue (url: https://pub.data.gov.bc.ca/datasets/949f2233-9612-4b06-92a9-903e817da659/)
  |===============================================================================================================================| 100%

**Error in if (ext == ".zip") { : missing value where TRUE/FALSE needed**

**Comment by ateucher** [comment]
This an issue with rems, which should be fixed in https://github.com/bcgov/rems/pull/55 - just waiting for some testing before I merge it and create a release

**Comment by joethorley** [comment]
This error is now fixed with the development version of rems https://github.com/bcgov/rems/issues/56

Feel free to reopen if it recurs.

@JessicaPenno - can you close this issue

**Comment by joethorley** [comment]
@KeithTStory Can you confirm (after installing the development version of rems using `devtools::install_github("bcgov/rems")` and shinyrems using `devtools::install_github("bcgov/shinyrems")`?

**Comment by JessicaPenno** [comment]
closed
