### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by JessicaPenno** [bcgov/shinyrems#124]
current instructions install an older version of ShinyREMs, this needs to be updated to reflect the latest updated of REMs (duckdb) and most recent version of ShinyREMs.

**Comment by HeatherGranger** [comment]
links to issue #127

**Comment by ateucher** [comment]
Just a note that the duckb branch of rems is not yet the default version - I think it warrants a bit more testing, especially with shinyrems. Note that the duckdb version does a better job of handling timezones, so if there was a 'fix' in place in shinyrems for that, then that will need to be looked at.

**Comment by HeatherGranger** [comment]
Remove dates from the section below as they are always changing as time goes forward:
‘2yr’ - uses most recent 2 years of EMS data (from 2018-01-01 to present)
‘4yr’ - uses most recent 4 years of EMS data from 2016-01-01 to present)
‘historic’ - uses historic EMS data (up to 2018-01-01)
