### ISSUE TITLE
historic/all data unzipping error

### ISSUE THREAD

**Issue by KarHarker** [bcgov/shinyrems#125]
Some users (not all) are having issues downloading the historic/all dataset. Data downloads to 100% but then the unzipping step gives this error: 

```
|=Error: The size of the connection buffer (131072) was not large enough
to fit a complete line:
  * Increase it by setting `Sys.setenv("VROOM_CONNECTION_SIZE")`
```

Tried to increase "VROOM_CONNECTION_SIZE" in env but still getting the same error

**Comment by ateucher** [comment]
Is this also happening in `rems` by itself?

**Comment by JessicaPenno** [comment]
yes, I just tried to download the historic database using rems and I got the same error as I am getting in ShinyREMs. I have tried increasing the connection size to as large as 10000000 and it still did not work. I got a second warning too:

In addition: Warning message:
In file.remove(db_path) :
  cannot remove file 'my file path'

**Comment by ateucher** [comment]
@JessicaPenno can you report what version of the `readr` package you have installed?

**Comment by JessicaPenno** [comment]
2.0.0 but i see there is a newer one

**Comment by JessicaPenno** [comment]
with updated readr i still get the vroom error but not the file path error @ateucher

**Comment by HeatherGranger** [comment]
This should be fixed as long as shinyrems works with rems duckdb #130

**Comment by HeatherGranger** [comment]
Fixed issue with addition of rems duckdb.
