### ISSUE TITLE
add option to download most recent historic dataset

### ISSUE THREAD

**Issue by KarHarker** [bcgov/shinyrems#126]
As the historic data now gets updated daily on DataBC - add option for users to update their historic dataset so you don't have to re-download everytime it opens

**Comment by HeatherGranger** [comment]
#130

**Comment by aylapear** [comment]
if this pull request is accepted it will deal with this issue 
https://github.com/bcgov/rems/pull/69

**Comment by aylapear** [comment]
@HeatherGranger this could be closed as the pull request in rems was accepted. Try the app with historic data set (after updating rems) and if it suits what you expected this can be closed. (same comment as other issue related to this)
