### ISSUE TITLE
Update users guide

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/shinyrems#127]
make current, adding information on:

- Upload data version and specifics around template

**Comment by HeatherGranger** [comment]
add blurb about vroom size error and that you may need to increase the size of the connection buffer:

|=Error: The size of the connection buffer (655360) was not large enough
to fit a complete line:
  * Increase it by setting `Sys.setenv("VROOM_CONNECTION_SIZE")`
> Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 10)

**Comment by KarHarker** [comment]
Spoke to soon! looks like Fig 17 didn't load properly @aylapear

**Comment by HeatherGranger** [comment]
@aylapear The figs are loaded, so just a couple formatting items to perfect. 
1) Tab 3 onward should all be under the 'Shinyrems features' heading like Tab 1 and Tab 2 are. 
2) Using the upload function content is rather large, need to make it 'normal' font like the rest of the text.
