### ISSUE TITLE
plots/statistics title order matching

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/shinyrems#134]
In tab 5: Plots/Statistics, on the right hand side: switch Summary Table and Guideline Data tabs to match the order in which they arrear on the left hand side grey menu.

**Comment by aylapear** [comment]
<img width="1145" alt="Screen Shot 2022-01-18 at 12 55 36 PM" src="https://user-images.githubusercontent.com/42985574/150017305-1df523fb-ed82-41ba-b8e9-50978a12385f.png">

**Comment by HeatherGranger** [comment]
that's right @aylapear. I think the order should be Plot, Guideline, Summary.
