### ISSUE TITLE
addition to users guide

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/shinyrems#148]
In the shinyrems summary table the lowerQ and upperQ represent 25% and 75%

**Comment by aylapear** [comment]
Hi @HeatherGranger, to confirm we are talking about the same thing I have provided two potential options. To highlight the change I have made the sentence italics (it would not be italic in the user guide). Let me know if one of these works and if so I can implement that change in the user guide. 

<br><br>

#### Option 1
Summary Table Tab

The Summary Table options allow for calculation of a summary table which can be downloaded as a .csv. The Summary Table gives a simple stats summary for each EMS_ID based on the clean dataset with outliers removed (Figure 15). Columns include n (number of water samples), ncen (number of censored values), min (minimum water value), max (maximum water value), mean (mean water value), median (median water value), lowerQ, upperQ, sd, se, lower CL and upper CL. *The lowerQ and upperQ represent 25% and 75%.*

#### Option 2
Summary Table Tab

The Summary Table options allow for calculation of a summary table which can be downloaded as a .csv. The Summary Table gives a simple stats summary for each EMS_ID based on the clean dataset with outliers removed (Figure 15). Columns include n (number of water samples), ncen (number of censored values), min (minimum water value), max (maximum water value), mean (mean water value), median (median water value), *lowerQ (25%), upperQ (75%)*, sd, se, lower CL and upper CL.

**Comment by HeatherGranger** [comment]
Thanks @aylapear - option 2 looks awesome.

**Comment by aylapear** [comment]
@HeatherGranger great, I will make that change in the user guide

**Comment by HeatherGranger** [comment]
Completed.

**Comment by aylapear** [comment]
Pull request #149
