### ISSUE TITLE
Water Quality Analysis Shiny App

### ISSUE THREAD

**Issue by bcdevex** [bcgov/shinyrems#21]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-water-quality-analysis-shinyapp"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-water-quality-analysis-shinyapp">visit the opportunity page</a>.
The opportunity closes on <b>Wednesday, August 21st, 2019 at 15:00 PDT</b>.</p>

**Comment by jpenn21** [comment]
Hi Folks: myself and @HeatherGranger are the Opportunity Contacts for this issue. Please post any questions you have here and we will do out best to respond promptly.

**Comment by mark-a-wilson** [comment]
Hi @jpenn21,
Would you mind re-opening this issue and closing it off with a comment when the code has been delivered and you're ready to pay? ([See these guidelines](https://github.com/BCDevExchange/code-with-us/wiki/2.-For-Public-Sector-Employees:-How-to-Manage-a-Code-With-Us-Opportunity#wrapping-up)) Thanks! This just helps me keep track of the outcomes of all the _Code With Us_ opportunities.

**Comment by JessicaPenno** [comment]
Closed with the following pull request: ShinyRems Update # 59 which completes Phase 1  development of the Water Quality Analysis ShinyApp. 

Excellent work team!
