### ISSUE TITLE
generate report tab

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/shinyrems#23]
there could be checkboxes for which results to include in summary report (e.g. plot, summary table, map, table as appendix)

**Comment by joethorley** [comment]
good question - or simpler to let the user edit them out of the .Rmd report?

**Comment by sebdalgarno** [comment]
yes except I think would be good to have option to export as html or pdf for users less familiar with R?

**Comment by HeatherGranger** [comment]
Most users will be unfamiliar with the inner workings of R, so I think the checkboxes would be most effective to produce a summary report.

**Comment by sebdalgarno** [comment]
next year

**Comment by sebdalgarno** [comment]
no longer required
