### ISSUE TITLE
Project Deliverables

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/shinyrems#24]
### 1. Reformat interface to follow typical water quality data analysis workflow:
- [x]	Access data either directly from EMS or upload .csv file. Add function to rems to check data format and prompt user with helpful messages if incorrect. Add template.
- [x]	Search for single or multiple EMS ID(s), monitoring site name(s), permit number(s) and/or water quality parameters. Add function to rems to cache a lookup table locally, which will be used to automatically update available site/parameter drop downs and map markers based on user selection.
- [x] Search sites first, then select parameters
- [ ] Select reference site(s) for calculation of WQG
- [x]	Ability to select sites from the interactive map or dropdown
- [x] Zoom to map by watershed group (dropdown or click on polygon)
- [x]	Select dates
- [x]	Options to refine raw dataset (see 2A)
- [x]	Provide a variety of plotting options (see 2B)
- [ ]	Input water quality benchmark (defined number) or calculate water quality guideline to be added to plot
- [x]	Options to calculate basic summary statistics for the dataset
#### A. Refining Raw Dataset
- [x]	Add drop down menus for the following EMS columns to select one or more option: SAMPLE_STATE, SAMPLE CLASS
- [x] add option to differentiate between 'Regular' and 'Replicate' sample class. The function clean-wqdata.R currently averages 'Replicates' (two or more readings for the same variable on the same date) with 'Regular' sample class
- [x]	Option to retain data collected on the same day but at different depths (UPPER_DEPTH, LOWER_DEPTH) as individual data points
- [x]	Manually remove outliers by selecting a row of the interactive table (DT R package) or a point on the plot
- [x] Add rules for detecting outliers. Manual selection overrides rule.
#### B. Censored Data
- [ ] Implement scientifically defensible statistical approach for estimating censored data (data below detection limits). This includes methods for dealing with single or multiple detection limits and small and large sample sizes, using nonparametric methods and Maximum Likelihood Estimations.  One approach could be using the CRAN Package NADA (Non-detects and Data Analysis for Environmental Data: https://CRAN.R-project.org/package=NADA). The approach to dealing with censored data will require working with the Water Quality Team.
#### C. Plotting
- [x]	Option to select second parameter to graph if in the same units (e.g., total and dissolved copper)
- [x]	Add faceted plots for comparing parameters in different units (e.g., total and dissolved copper with total suspended solids)
- [x]	Default graph scatter plot, option for time series and box plots
- [x]	Units added to y axis
- [x]	Distinguish <MDL (data below detection limits) from data results
- [x]	Option to display legend
- [x] Option to change site names (reflected in legend and as new column in data/table.
- [x] Option to refine dataset timeframe (by min/max time and season)
#### D. Summary Statistics
- [x] Tabulation of basic summary statistics (n, min, max, mean, median, SE, SD; Options for quantiles, percentiles, upper/lower confidence intervals). View summary statistics in a tab of the results panel (added function to wqbc)
#### E. Water Quality Guidelines/Benchmarks
- [ ]	Calculate  water quality guideline (existing script in wqbc package: calc-limits.R, may require updates/modifications) for guidelines that are based on other parameters (i.e., hardness, pH, temperature)
- [ ]	Option to manually enter guideline, permit limit, other benchmark
- [ ]	Add function to wqbc to access limits from a lookup table on DataBC
- [ ]	Add water quality guideline or desired benchmark to plot
- [ ]	Work with wqbc code (calc-limits.R) which models guideline value for dependent parameters (pH, total chloride or total hardness) when data is missing
- [ ]	Modelled water quality guideline =  line different in look and name from regular calculated guideline
- [ ]	Message asking user if they want to model guideline (i.e., "Insufficient [parameter (e.g., hardness)] data to calculate water quality guideline, do you want to proceed with an estimate based on a model?")
- [ ]	Change 'limit' reference to 'guideline'
- [ ]	Retain all parameters even if there is no water quality guidelines. At this time, the calc-limits.R function drops all parameters without a water quality guideline once it is run
#### F. Outputs
- [x]	Ability to export data in .csv and plot in .png file in App
- [ ]	View a summary document in a tab of the navigation bar and download as HTML, pdf or RMarkdown
- [ ] Option to check which results included in summary document
- [ ]	View R code to reproduce results in a tab of the navigation bar and download as an R script (implemented using shinymeta R package)
- [x]	Customize name of plot or table when exporting
- [ ]	Add users guide to App (Water Quality Team will provide content for this)

Outputs 	 
The Contractor must provide the Province with water quality shiny app: a reviewed & approved Pull Request adding source code that generates a shiny app output with the above stated reformatting and additional functions. In addition, a reviewed and approved Pull Request for rems and wqbc adding code for the necessary functionality for the shiny app changes.

**Comment by HeatherGranger** [comment]
Looks great. I'm not sure if `rems` is the best place to put the .csv upload functionality given it focuses on downloading EMS data. We'll have to bring Andy in to see what he thinks when we get there.

**Comment by sebdalgarno** [comment]
Yes that makes sense. That function (i.e. just to check that csv fits a certain format) can easily just live inside shinyrems package.

**Comment by sebdalgarno** [comment]
phase 1 complete - closing now
