### ISSUE TITLE
Notes on censored data

### ISSUE THREAD

**Issue by joethorley** [bcgov/shinyrems#35]
In *general*, MLE is fast and does not require input from the user and gives exactly the same answer each time but makes it difficult to capture the uncertainty  - it also requires ‘sufficient' sample size.
Bayesian is slower and requires the user to specify prior distributions and has a stochastic element but is completely customizable and not dependent on the sample size for its validity.

I generally model in the Bayesian framework but think MLE is often better suited to user interfaces particularly if the desired outputs are simple transforms of the model coefficients and we can ensure sufficient sample size.

I think we should go the MLE route. NADA has seems to have enough flexibility through it’s model formulaic approach if we ignore autocorrelation… if we want to deal with it then it would require us to model using a MLE templating based language like TMB.

> We’ve put together 5 dataset conditions and we think applying the most appropriate approach to these datasets based on your expertise would make the most sense.  We recognize one approach may not fit all these conditions.
> The types of datasets we are usually reviewing include data that are:
>a.      regularly sampled throughout year (monthly, quarterly etc.)
> b.      sporadic, low number of datapoints
> c.       seasonal (growing season, spring or fall turnover etc.)

Models could potentially include a long-term trend (possibly polynomial) as well as a seasonal component (modelled as a sinusoidal).
Modelling non-independence would be more challenging

> Other things:
-This would be optional for the user; censored data options are not automatically applied to the dataset

Yes I think the user should be able to analyse censored data as censored or set it to be 0, 1/2 MDL or MDL ie 4 options (but see below)

> -How would these censored data approach’s address changing MDL's over time? Would these datasets with different MDLs have to be analysed separately?

No both the MLE and Bayesian frameworks can readily handle unique MDLs for each data point.

> -At what point is it not correct to model? Aka, when could we bring in substitution? Some folks wanted to keep this option.

Strictly speaking it’s never correct to substitute. I think its good to offer these options but only for historical reasons and to have the censored data as the default approach.

> -We put 3 arbitrarily in the dataset conditions, but could be changed to a move statistical supported value based on what you think.

I think it should be 1.

With regard Group 1 there is Insufficient data to analyse without strong prior information.

Group | Dataset Conditions | Censored data approach
-- | -- | --
1 | All dataset is non-detects | ?
2 | 0 < % non-detects < 100 AND # detects < 3 (less than 3 detected measurements) | ?
3 | 0 < % non-detects < 100 AND # detects ≥ 3 (greater than 3 detected measurements) | ?
4 | ½ of dataset is non-detects, 1/2 of dataset is detected | ?
5 | % non-detects = 0 (all data is detected) or a very small number of non-detects | Substitution (1/2 MDL, MDL) if only a small number of datapoints are not-detected?

**Comment by joethorley** [comment]
Objective

B. Censored Data

Implement scientifically defensible statistical approach for estimating censored data (data below detection limits). This includes methods for dealing with single or multiple detection limits and small and large sample sizes, using nonparametric methods and Maximum Likelihood Estimations. One approach could be using the CRAN Package NADA (Non-detects and Data Analysis for Environmental Data: https://CRAN.R- project.org/package=NADA). The approach to dealing with censored data will require working with the Water Quality Team.

**Comment by sebdalgarno** [comment]
@joethorley can i close this issue now?

**Comment by sebdalgarno** [comment]
I think this is closed now, but waiting on Joe to confirm

**Comment by sebdalgarno** [comment]
@joethorley can you close this issue please
