### ISSUE TITLE
Changing standard deviation input box causes error.

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/shinyrems#37]

**Comment by sebdalgarno** [comment]
@HeatherGranger I'm not able to reproduce the error. Have you installed the latest version?
remotes::install_github("poissonconsulting/shinyrems")

**Comment by HeatherGranger** [comment]
It works! I must not have had the latest version. Thanks.

**Comment by sebdalgarno** [comment]
OK please close @HeatherGranger (I don't have the privilege to close an issue you created)
