### ISSUE TITLE
Summary stats download error in tab 5.

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/shinyrems#38]

**Comment by sebdalgarno** [comment]
@HeatherGranger its working for me. Have you installed the latest version?
`remotes::install_github("poissonconsulting/shinyrems")`

**Comment by sebdalgarno** [comment]
@HeatherGranger can you confirm this is still happening?

**Comment by HeatherGranger** [comment]
@sebdalgarno I can't get there as there's an error in the clean function (i'll make a new issue), but likely ok as I have the latest version now.
