### ISSUE TITLE
match Variables in limits

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/shinyrems#45]
Variables in limits sheet different from Variables in EMS database
need to add lookup

**Comment by HeatherGranger** [comment]
@sebdalgarno I thought I had matched the Variable names in EMS in the latest limits.csv I had edited. Let me know if you need me to check anything on this.

**Comment by sebdalgarno** [comment]
yes you're right @HeatherGranger - I should be able to match by EMS_CODE.
I'll let you know if any EMS_CODES can't be matched, but probably this isn't an issue

**Comment by sebdalgarno** [comment]
done
