### ISSUE TITLE
Download Template error in 'upload' uption

### ISSUE THREAD

**Issue by HeatherGranger** [bcgov/shinyrems#50]
Error message:
`Warning: Error in : Assigned data `template[[i]][["type"]]` must be compatible with existing data.
i Error occurred for column `Value`.
x No common type for `value` <character> and `x` <double>.
  [No stack trace available]`

Session info:
- Session info ---------------------------------------------------------
 setting  value
 version  R version 3.6.3 (2020-02-29)
 os       Windows 10 x64
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_Canada.1252
 ctype    English_Canada.1252
 tz       America/Los_Angeles
 date     2020-03-30
- Packages -------------------------------------------------------------
 package         * version    date       lib
 assertthat        0.2.1      2019-03-21 [1]
 backports         1.1.5      2019-10-02 [1]
 bit               1.1-15.2   2020-02-10 [1]
 bit64             0.9-7      2017-05-08 [1]
 blob              1.2.1      2020-01-20 [1]
 callr             3.4.3      2020-03-28 [1]
 checkr            0.5.0      2019-04-25 [1]
 chk               0.4.0      2020-03-04 [1]
 cli               2.0.2      2020-02-28 [1]
 crayon            1.3.4      2017-09-16 [1]
 crosstalk         1.1.0.1    2020-03-13 [1]
 curl              4.3        2019-12-02 [1]
 DBI               1.1.0      2019-12-15 [1]
 desc              1.2.0      2018-05-01 [1]
 devtools          2.2.2      2020-02-17 [1]
 digest            0.6.25     2020-02-23 [1]
 dplyr             0.8.5      2020-03-07 [1]
 DT                0.13       2020-03-23 [1]
 ellipsis          0.3.0      2019-09-20 [1]
 err               0.2.0      2019-04-25 [1]
 fansi             0.4.1      2020-01-08 [1]
 fastmap           1.0.1      2019-10-08 [1]
 fs                1.3.2      2020-03-05 [1]
 glue              1.3.2      2020-03-12 [1]
 hms               0.5.3      2020-01-08 [1]
 htmltools         0.4.0      2019-10-04 [1]
 htmlwidgets       1.5.1      2019-10-08 [1]
 httpuv            1.5.2      2019-09-11 [1]
 httr              1.4.1      2019-08-05 [1]
 jsonlite          1.6.1      2020-02-02 [1]
 later             1.0.0      2019-10-04 [1]
 leaflet           2.0.3      2019-11-16 [1]
 lifecycle         0.2.0      2020-03-06 [1]
 lubridate         1.7.4      2018-04-11 [1]
 magrittr          1.5        2014-11-22 [1]
 memoise           1.1.0      2017-04-21 [1]
 mime              0.9        2020-02-04 [1]
 pillar            1.4.3      2019-12-20 [1]
 pkgbuild          1.0.6      2019-10-09 [1]
 pkgconfig         2.0.3      2019-09-22 [1]
 pkgload           1.0.2      2018-10-29 [1]
 prettyunits       1.1.1      2020-01-24 [1]
 processx          3.4.2      2020-02-09 [1]
 promises          1.1.0      2019-10-04 [1]
 ps                1.3.2      2020-02-13 [1]
 purrr             0.3.3      2019-10-18 [1]
 R6                2.4.1      2019-11-12 [1]
 rappdirs          0.3.1      2016-03-28 [1]
 Rcpp              1.0.4      2020-03-17 [1]
 readr             1.3.1      2018-12-21 [1]
 remotes           2.1.1      2020-02-15 [1]
 rems              0.5.1      2020-03-26 [1]
 rlang             0.4.5      2020-03-01 [1]
 rprojroot         1.3-2      2018-01-03 [1]
 RSQLite           2.2.0      2020-01-07 [1]
 rstudioapi        0.11       2020-02-07 [1]
 sessioninfo       1.1.1      2018-11-05 [1]
 shiny           * 1.4.0.2    2020-03-13 [1]
 shinycssloaders   0.3        2020-01-16 [1]
 shinyjs           1.1        2020-01-13 [1]
 shinyrems         0.0.0.9001 2020-03-31 [1]
 storr             1.2.1      2018-10-18 [1]
 stringi           1.4.6      2020-02-17 [1]
 stringr           1.4.0      2019-02-10 [1]
 testthat          2.3.2      2020-03-02 [1]
 tibble            3.0.0      2020-03-30 [1]
 tidyselect        1.0.0      2020-01-27 [1]
 usethis           1.5.1      2019-07-04 [1]
 vctrs             0.2.4      2020-03-10 [1]
 waiter            0.1.0      2020-01-14 [1]
 withr             2.1.2      2018-03-15 [1]
 wqbc              0.3.1.9002 2020-03-26 [1]
 xml2              1.2.5      2020-03-11 [1]
 xtable            1.8-4      2019-04-21 [1]
 yaml              2.2.1      2020-02-01 [1]
 source
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.2)
 CRAN (R 3.6.0)
 CRAN (R 3.6.2)
 CRAN (R 3.6.3)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.3)
 CRAN (R 3.6.1)
 CRAN (R 3.6.3)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.2)
 CRAN (R 3.6.3)
 CRAN (R 3.6.3)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.2)
 CRAN (R 3.6.1)
 CRAN (R 3.6.3)
 CRAN (R 3.6.3)
 CRAN (R 3.6.2)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.2)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.2)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.2)
 CRAN (R 3.6.2)
 CRAN (R 3.6.1)
 CRAN (R 3.6.2)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.1)
 CRAN (R 3.6.3)
 Github (bcgov/rems@d4ea4ce)
 CRAN (R 3.6.3)
 CRAN (R 3.6.1)
 CRAN (R 3.6.2)
 CRAN (R 3.6.2)
 CRAN (R 3.6.1)
 CRAN (R 3.6.3)
 CRAN (R 3.6.1)
 CRAN (R 3.6.2)
 Github (poissonconsulting/shinyrems@8d0d9d4)
 CRAN (R 3.6.1)
 CRAN (R 3.6.2)
 CRAN (R 3.6.1)
 CRAN (R 3.6.3)
 CRAN (R 3.6.1)
 CRAN (R 3.6.2)
 CRAN (R 3.6.1)
 CRAN (R 3.6.3)
 CRAN (R 3.6.2)
 CRAN (R 3.6.1)
 Github (bcgov/wqbc@aed7b38)
 CRAN (R 3.6.3)
 CRAN (R 3.6.1)
 CRAN (R 3.6.2)
[1] C:/Users/hthmps/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.3/library

**Comment by sebdalgarno** [comment]
hi @HeatherGranger can you please close this issue? it's resolved now
