### ISSUE TITLE
Use wqbc::summary_wqdata() to calculate summary statistics

### ISSUE THREAD

**Issue by joethorley** [bcgov/shinyrems#53]
Once pull request https://github.com/bcgov/wqbc/pull/136 has been merged

**Comment by joethorley** [comment]
Not yet merged. - will update when done so.

**Comment by joethorley** [comment]
Ready to add when this pull request is merged https://github.com/bcgov/wqbc/pull/138

Note it should be made available after data have been cleansed in the shiny app.

**Comment by sebdalgarno** [comment]
done

**Comment by sebdalgarno** [comment]
@joethorley can you close this? (I don't have privileges)

**Comment by joethorley** [comment]
done
