### ISSUE TITLE
phase 2 - Improve matching lookup_codes to variables

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/shinyrems#71]
@HeatherGranger to work on this

**Comment by HeatherGranger** [comment]
Working on this as per issue #43 in wqbc.

**Comment by joethorley** [comment]
@HeatherGranger - if you put a # in front of the issue number then it forms an automatic link like this

#43

**Comment by HeatherGranger** [comment]
I don't want to link to issue 43 here - can I link to an issue in another repo?

**Comment by joethorley** [comment]
Right!

bcgov/wqbc#43

**Comment by joethorley** [comment]
@HeatherGranger and @JessicaPenno  - I think we can close this issue as bcgov/wqbc#143 is closed.

**Comment by sebdalgarno** [comment]
I'll close it Joe
