### ISSUE TITLE
phase 2 - Guideline calculation info

### ISSUE THREAD

**Issue by sebdalgarno** [bcgov/shinyrems#74]
differentiate   wrong parameter or selected parameter doesn't have guideline (point to ref   table) or insufficient data errors, provide bigger markdown message on how to   get guideline calculated and what the options mean, specify guidelines are   for aquatic life.

ENV-Check with WQG team after we   have wording explaining what modelled estimate is doing.      Seb provide what's going on behind scences, ENV to refine message.

**Comment by joethorley** [comment]
This is being dealt with by https://github.com/bcgov/wqbc/issues/147

**Comment by joethorley** [comment]
Can the WQG team (@HeatherGranger, @JessicaPenno) provide example data sets?

**Comment by sebdalgarno** [comment]
one example error that isnt informative:
Arsenic Total in "all" dataset with 'Shuswap Lk TB # 5' station
 I get:
```
Error in UseMethod("filter_") : no applicable method for 'filter_' applied to an object of class "NULL"
```
heather gets: 
```
x and y must share the same src, set copy = TRUE (may be slow)
```

different msgs possibly due to different wqbc  versions?

**Comment by sebdalgarno** [comment]
done
